---
- name: Install Redis
  hosts: localhost
  vars:
    redis_port: 6379
    redis_databases: 1
  tasks:
    - name: Install redis
      dnf:
        name: redis
        state: latest      

    - name: Ensure Redis is started
      service: 
        name: redis
        state: started 
        enabled: yes
    
    - name: chnage config file
      lineinfile:
        path: '/etc/redis.conf'
        regex: '^requirepass'
        line: "requirepass admin123"
      notify: Redis Restart
        
        
    - name: chnage config file
      lineinfile:
        path: '/etc/redis.conf'
        regex: '^tcp-keepalive'
        line: "tcp-keepalive 60"
      notify: Redis Restart
        
    - name: chnage config file
      lineinfile:
        path: '/etc/redis.conf'
        regex: '^port'
        line: "port 6379"
      notify: Redis Restart   
      
    - name: chnage config file
      lineinfile:
        path: '/etc/redis.conf'
        regex: '^protected-mode'
        line: "protected-mode no"
      notify: Redis Restart
      
    - name: chnage config file
      lineinfile:
        path: '/etc/redis.conf'
        regex: '^loglevel'
        line: "loglevel  notice"
      notify: Redis Restart  
    
    - name: chnage config file
      lineinfile:
        path: '/etc/redis.conf'
        regex: '^appendonly'
        line: "appendonly yes"
      notify: Redis Restart    
        
    - name: chnage config file
      lineinfile:
        path: '/etc/redis.conf'
        regex: '^logfile'
        line: "logfile  /var/log/redis/redis.log"
      notify: Redis Restart    
          
    - name: Bind redis to 172.31.89.158
      lineinfile:
        dest: '/etc/redis.conf'
        regexp: '^bind'
        line: 'bind 127.0.0.1 172.31.89.158'
        state: present
      notify: Redis Restart
       
  handlers:

    - name: Redis Restart
      service: 
        name: redis 
        state: restarted 
        enabled: yes
        sudo: true
